from typing import Any, List, Sequence, Text, Tuple

class Cursor:
    closed: bool
    description: Tuple[Any]
    def execute(self, query: Text, args: Sequence[object] = ...) -> None: ...
    def fetchall(self) -> List[Tuple[Any, ...]]: ...
    def close(self) -> None: ...

class Connection:
    dbname: Text
    def cursor(self, serialized: bool = ...) -> Cursor: ...

def db_connect(to: Text, allow_uri: bool = ...) -> Connection: ...
