from typing import Any, Dict, Optional, Sequence, Text, Union

class _configmanager:
    options: Dict[Text, Union[str, bool, int]]
    def __getitem__(self, key: Text) -> Any: ...
    def __setitem__(self, key: Text, value: Union[str, bool, int]) -> None: ...
    def parse_config(self, args: Optional[Sequence[Text]] = ...) -> None: ...

config: _configmanager
