from typing import Any, Dict, Optional, Sequence, Text, Union

_ConfigValue = Union[str, bool, int]

class _configmanager:
    options: Dict[Text, _ConfigValue]
    def __getitem__(self, key: Text) -> Any: ...
    def __setitem__(self, key: Text, value: _ConfigValue) -> None: ...
    def get(self, key: Text, default: _ConfigValue = ...) -> Optional[_ConfigValue]: ...
    def parse_config(self, args: Optional[Sequence[Text]] = ...) -> None: ...

config: _configmanager
